### ISSUE TITLE
code : how is start position defined ?

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#24]
in your README you state:

> Both "position fen [fen]" and "position startpos" are ignored.

indeed, if you want a very simple engine which can only play from the startposition, you don't need those .. but when i look into the source of `main.cpp` (although i'm not a C++ programmer) i discover no definition of the start position .. i wanted to adjust the code a little to implement some `position fen [..]` command - just for learning. Your code seems readable though ..

**Comment by kz04px** [comment]
The Position struct initialises the values to that of startpos.

```C++
struct [[nodiscard]] Position {
    array<BB, 2> colour = {0xFFFFULL, 0xFFFF000000000000ULL};
    array<BB, 6> pieces = {0xFF00000000FF00ULL,
                           0x4200000000000042ULL,
                           0x2400000000000024ULL,
                           0x8100000000000081ULL,
                           0x800000000000008ULL,
                           0x1000000000000010ULL};
    BB ep = 0x0ULL;
    array<int, 4> castling = {true, true, true, true};
    int flipped = false;
};
```

Then when a UCI `position` command is received, the position is reset to startpos before later parsing `moves`.
```C++
} else if (word == "position") {
    pos = Position();
    hash_history.clear();
}
```

This limitation means that to work under CuteChess or anywhere else, the current position must be supplied as a sequence of moves from startpos, and not as a FEN.

**Comment by tissatussa** [comment]
thanks
