### ISSUE TITLE
endgame skills

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#27]
these days i keep testing your (newest) 4KU2 version(s) .. it seems 4KU2 plays the endgame rather well, but i saw some severe mistakes .. here are two examples, 4KU2 played Black in both games.

this is from the game against Little Wing v0.7.0 (2169).
FEN: `8/6k1/5pp1/2Q5/4K1Pp/P4Pq1/8/8 b - - 0 45`
both teams have equal material, it's a difficult endgame where both players only have a Queen and a few pawns .. here accurate moves are required : win, loss or draw are all possible .. Black has only 1 move which wins : ...Qe1+. Your 4KU2 finds it, but does not win the game, it ended in a draw. 

![littlewing-vs-4ku2_draw_but_could_win](https://user-images.githubusercontent.com/1109281/204313171-35c05252-1b9f-4672-b7e3-7c634ff1fec6.png)

this is from the game against Dabbaba v6.52 (1939).
FEN: `8/8/8/8/2k2p2/5P1p/4K2P/8 b - - 0 65`
both teams have equal material, it's a drawn endgame but 4KU2 tries to win .. here Black must not let the White King come to d3, but this is what happened and 4KU2 lost ..

![dabbaba-vs-4ku2_lost_but_could_draw](https://user-images.githubusercontent.com/1109281/204313224-21b13e81-9b62-4eaa-9a96-49ec4db3f80d.png)

**Comment by kz04px** [comment]
4ku will have to work out endgames entirely by itself, as the code required for EGTB is far too large. While they can be tricky, I don't foresee any patches being made specifically for them.

I would say the best way for 4ku to get better at endgames is to get better at chess in general.

**Comment by tissatussa** [comment]
i just created [#39] for it.
