### ISSUE TITLE
save byte by deleting some lines

### ISSUE THREAD

**Issue by ghost** [kz04px/4ku#296]
Hi 
you can save some byte if you delete these lines (in the main function) after the line
goto search_start;
           
            cin >> word >> time_left;
            if (pos.flipped)
               cin >> word >> time_left;

these lines are never used.

**Comment by MinusKelvin** [comment]
They are used in the minified version, since in that version the `goto search_start;` line is removed as it is within the `// minify enable filter delete` section.
