### ISSUE TITLE
about Hash usage

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#31]
i'm still testing the (newest) 4KU2 versions by compiling them and let them play with several engines in CuteChess (on Linux). I gathered a lot of (weaker) open source engines and i try to match opponents with similar rating - my current guess of 4KU2 rating is 2100. These are all seperate games (10 min + 3 sec bonus), i mean i do no tournament in CuteChess.

i like your minimalistic approach .. although i'm not a C++ programmer (but mainly Python and JS), your code seems very well written and is just one small cpp file! The UCI subset which you use is enough for playing in CuteChess (or similar), it understands just "position startpos moves [...]" and "go wtime 603000 btime 603000 winc 3000 binc 3000" or similar.

i guess 4KU2 is not for playing in terminal, but it can be done. Looking at the games 4KU2 plays in CuteChess, i see it has a natural way of developing the pieces and pawns. Using the same time settings in all games, 4KU2 seems rather consistent in its openings, only a few times it plays another variation (when the opponent played known opening moves). I guess in such case both moves have almost equal eval, maybe the hash 'decided' the "best move" ?  To test a position with different settings, i used terminal by entering the proper (large) move list to reach that position .. i had some odd results, maybe hash is involved ? Then how ? Could such tests help your development ? Can you reproduce them anyway ? - myself i didn't redo the same terminal sessions to see if they would lead to the exact same results .. btw. i use a rather modern avx2 notebook and Xubuntu 22.04

i want to show the terminal output concerning this position :

![4KU2-pos-after-e4e5](https://user-images.githubusercontent.com/1109281/204861583-e2dfda0d-c21a-402a-85a6-46a1b00c9527.png)

```
UCI : position startpos moves e2e4 b8c6 d2d4 d7d5 e4e5
FEN : r1bqkbnr/ppp1pppp/2n5/3pP3/3P4/8/PPP2PPP/RNBQKBNR b KQkq - 0 3
```

This is a well known position in chess theory. Most positions can be reached by altered move order, but normally the game went like this :

1. e4 Nc6

This opening is called the Nimzowitch Defence. 4KU2 also prefers e4 on move 1, but with Black it would answer the good standard e7e5 :

```
ucinewgame
id name 4ku2
id author kz04px
uciok
position startpos moves e2e4                    
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove e7e5
```

Our game continues with :
2. d4 d5

4KU2 prefers Nf3 on move 2, but after 2.d4 it also prefers to answer d5 with Black :

```
position startpos moves e2e4 b8c6               
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove g1f3
position startpos moves e2e4 b8c6 d2d4          
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove d7d5
```

Our game continues with :
3. e5 ...

Here 4KU2 prefers not to advance the e-pawn, it likes to keep the initiative by e4xd5 :

```
position startpos moves e2e4 b8c6 d2d4 d7d5     
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove e4d5
position startpos moves e2e4 b8c6 d2d4 d7d5 e4e5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
```

We reached the position of the diagram. Here 4KU2 seems to prefer 3...f6 when given 10 minutes (per game), but when i let 4KU2 think again (same hash?) it finds other moves too ?! :

```
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
quit
```

And what about my test below (after restarting 4KU2 in terminal) .. same position, other best move :
(Note: the move Bd7 was once picked also)

```
ucinewgame
id name 4ku2
id author kz04px
uciok
position startpos moves e2e4 b8c6 d2d4 d7d5 e4e5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove f7f6
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8d7
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
go wtime 603000 btime 603000 winc 3000 binc 3000
bestmove c8f5
quit
```

And this test, using a longer time :

```
ucinewgame
id name 4ku2
id author kz04px
uciok
position startpos moves e2e4 b8c6 d2d4 d7d5 e4e5
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove f7f6
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove f7f6
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove c8f5
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove c8f5
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove c8f5
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove f7f6
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove c8f5
go wtime 1603000 btime 1603000 winc 3000 binc 3000
bestmove f7f6
quit
```

Here, the two moves Bf5 and f6 (which indeed are best according to SF) are both 'best move' after some time, but why do they toggle ?

**Comment by kz04px** [comment]
> Here, the two moves Bf5 and f6 (which indeed are best according to SF) are both 'best move' after some time, but why do they toggle ?

I suppose the two moves are just scored about equally and 4ku can't really pick between them. Searching on the same position multiple times is not necessarily going to return the same results. Each search still runs in its entirety and uses TT entries from previous searches.

If you want, you can now use one of the executables for testing purpose that have info strings included:
```
./4ku-normal
uci
id name 4ku
id author kz04px
uciok
isready
readyok
position startpos moves e2e4 b8c6 d2d4 d7d5 e4e5
go wtime 1603000 btime 1603000 winc 3000 binc 3000
info depth 1 score cp 43 pv c8f5
info depth 2 score cp 12 pv c8f5
info depth 3 score cp 21 pv c8f5
info depth 4 score cp -6 pv c8f5
info depth 5 score cp 18 pv c8f5
info depth 6 score cp -7 pv c8f5
info depth 7 score cp 0 pv c8f5
info depth 8 score cp -5 pv c8f5
info depth 9 score cp 1 pv f7f6
info depth 10 score cp 0 pv f7f6
info depth 11 score cp -6 pv f7f6
info depth 12 score cp -26 pv f7f6
info depth 13 score cp -20 pv f7f6
info depth 14 score cp -29 pv f7f6
bestmove f7f6
go wtime 1603000 btime 1603000 winc 3000 binc 3000
info depth 1 score cp 43 pv c8f5
info depth 2 score cp 12 pv c8f5
info depth 3 score cp 21 pv c8f5
info depth 4 score cp 0 pv f7f6
info depth 5 score cp 0 pv f7f6
info depth 6 score cp 0 pv f7f6
info depth 7 score cp 0 pv f7f6
info depth 8 score cp 0 pv f7f6
info depth 9 score cp 0 pv f7f6
info depth 10 score cp 0 pv f7f6
info depth 11 score cp 0 pv f7f6
info depth 12 score cp 0 pv f7f6
info depth 13 score cp 0 pv f7f6
info depth 14 score cp 0 pv f7f6
info depth 15 score cp 0 pv f7f6
info depth 16 score cp 0 pv f7f6
info depth 17 score cp 0 pv f7f6
bestmove f7f6

```

**Comment by tissatussa** [comment]
> use one of the executables for testing purpose that have info strings included

very nice! i see you made this addition in the main branch .. after compilation it runs fine in CuteChess, which indeed shows those info lines, just simple, no PV .. that's OK, your main goal seems creating a good engine within x bytes, i'm fine with that also. For testing i now use the well known pgn-extract binary, it can easily convert a pgn game into a sequence of moves, as required, then counting upto the concerning move ply gives me the proper `position startpos moves [..]` string.

this is really a very useful addition, thanks.

**Comment by tissatussa** [comment]
i suppose TT is Hash, to me your cpp code looks like it .. do you use a standard amount Mb ? I can't see that in the code .. and can the Hash / TT be cleared ? If not, that's OK. Or maybe a user Hash setting is not useful ?

**Comment by tissatussa** [comment]
so, your answer shows that Hash / TT indeed is causing the move 'toggle' ? Then my thoughts were right, i guess .. can you elaborate a bit about this (strange?) fluctuating behaviour ? One could expect the engine giving the same best move everytime, eg. after a restart ..

**Comment by kz04px** [comment]
> do you use a standard amount Mb ?

TT size is currently specified in number of entries rather than megabytes. 2 million entries at 32 bytes each is 64 megabytes.
You can find and change the engine "options" here:
```C++
const int MAX_TT_SIZE = 2000000;
const int thread_count = 1;
```

> can the Hash / TT be cleared ?

Absolutely. The `ucinewgame` command will clear the TT entirely. All engines should do this.

> maybe a user Hash setting is not useful ?

There are plans to introduce UCI `setoption` so that hash size and number of search threads can be set when the engine is running, but this hasn't yet been implemented. It'd be useful so 4ku can more easily play in tournaments where these values must be set for fairness.

**Comment by kz04px** [comment]
> so, your answer shows that Hash / TT indeed is causing the move 'toggle' ? ... can you elaborate a bit about this (strange?) fluctuating behaviour ?

When searching, positions and information about them like evaluation are entered into the TT (transposition table). Later in the search, or even in a different search entirely, the engine can check whether a position is already stored in the TT. If a position is already in the TT, then the information stored can be used again instead of working it out for a second time. For example, if the position after `1. e3 e6 d3 d6` is searched and stored in the TT, then we can arrive at the same position through transposition with the moves `1. d3 d6 e3 e6`. Instead of searching this second (and identical) position twice and wasting time, we can instead use the information inside the TT. This speeds up the search as it's far more efficient.

> One could expect the engine giving the same best move everytime, eg. after a restart ..

If you search the same position twice then the TT entries from the first search might change the results of the second search. If you either clear the TT (using `ucinewgame`) or restart the engine between the two searches, then the output should be more or less the same. There are some things that can still change the outcome though, such as precise timing on how long the engine searched for.

**Comment by tissatussa** [comment]
Thanks for this info. When i think about it, i wonder how this Hash / TT mechanism works in practice : when the Hash is big, doesn't it take (too much) time looking for a (transposed) position? And will positions, which can no longer occur, be removed from the Hash ? Therefor i guess the Hash should not be too big, to be efficient ? Some engines have a default Hash 1 Mb, while others use default eg. 256 Mb ..

**Comment by kz04px** [comment]
> when the Hash is big, doesn't it take (too much) time looking for a (transposed) position?

The TT entries are stored in an array or equivalent. The hash of the position is used to figure out where in the array the relevant entry might be found. This is usually done in the form `index = hash mod num_entries`. This means that finding the entry we want always costs the same regardless of the TT's size - one RAM lookup. Of course, the CPU cache might mean this isn't practically true all the time.

> And will positions, which can no longer occur, be removed from the Hash ?

No. The only way entries are removed from the TT are if `ucinewgame` is called, or if they get overwritten by new entries.

> i guess the Hash should not be too big, to be efficient ? Some engines have a default Hash 1 Mb, while others use default eg. 256 Mb ..

If a very large TT size is used on a very short search, then the search won't have enough time to fill the TT with useful information - it will be mostly empty. In this sense, I would say the TT is inefficient in its RAM usage.
In terms of strength, I don't see how increasing the TT size could be worse. Though again, perhaps if the TT fits entirely into the CPU's cache things might be different? Engines on very strong hardware, like at the TCEC, will use 10s of GBs for their TT.
