### ISSUE TITLE
handle equal eval with more time ?

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#37]
i was wondering : while testing some UCI engines with some interesting position, i stumbled upon the fact that 2 or more moves might have equal eval (cp) .. i'm using MultiPV for that .. i'm not asking for MPV in 4KU here, but does it have some table alike while calculating ? Sometimes, early in a game, 4KU thinks for 2 minutes while doing about 30 sec most moves : did the top variations have such equal eval and 4KU took more time / depth to distinguish ?

**Comment by kz04px** [comment]
4ku makes no attempt to distinguish between moves that score equally. It will simply favour the first one it found.
