### ISSUE TITLE
smart hard coded end game pattern ?

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#40]
i was wondering : some (weaker) engines can not do mate with only B & N, they don't know the concerning 'pattern' and often lose by 50 moves .. maybe 4KU can solve it ? Until now i did not test that .. without having a #-piece-end-game-TB, is some hard coded KKBN pattern allowed ? Does such even exist in chess programming ?

**Comment by kz04px** [comment]
I just added FEN support to the UCI `position` command. In a 5 minute game I ran against Stockfish, 4ku was unable to win the position shown [here](https://lichess.org/analysis/4k3/8/8/8/8/8/8/4KBN1_w_-_-_0_1).

Some engines do indeed have code specifically to play certain endgames, but I think this would take up a significant amount of space in return for very little Elo. 4ku's best chance of solving these is probably to just get stronger in general. Currently it has no knowledge of the 50 move rule, though I don't know if adding it would meaningfully help here.

**Comment by tissatussa** [comment]
> I just added FEN support to the UCI position command.

nice!
but you found a way to preserve bytes and only use `go startposition moves [#]` to simplest enter any position .. does only the non-minified version contain this FEN feature?

> Some engines do indeed have code specifically to play certain endgames, but I think this would take up a significant amount of space in return for very little Elo.

you're right .. and i didn't know of any engine having such hard coded endgames .. do you have an example / URL, eg. on GitHub ? Thanks, i'm interested.

> 4ku's best chance of solving these is probably to just get stronger in general.

you stated that before and i think it's a good vision, esp. when creating a simple but strong engine.

> Currently it has no knowledge of the 50 move rule, though I don't know if adding it would meaningfully help here.

Right again i think, same reason.
I keep following your versions and thanks for your feedback.

**Comment by kz04px** [comment]
> but you found a way to preserve bytes and only use go startposition moves [#] to simplest enter any position .. does only the non-minified version contain this FEN feature?

Correct.

> you're right .. and i didn't know of any engine having such hard coded endgames .. do you have an example / URL, eg. on GitHub ? Thanks, i'm interested.

I don't know if this code is still in use or how much if any Elo it adds, but I think Stockfish does it [here](https://github.com/official-stockfish/Stockfish/blob/master/src/endgame.cpp).

> thanks for your feedback

Thank you for yours.
