### ISSUE TITLE
python subprocess : catch both stdout and stderr ?

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#41]
the following code line works with most UCI engines :

```python
p = Popen( [ "sh", "my/path/to/engine/run.sh" ], stdout=PIPE, stdin=PIPE, universal_newlines=True )
```

those engines only seem to use stderr for their starting "uci settings output", their info lines are all in stdout, which i can catch and filter .. for my script i don't need the stderr info .. however, 4KU seems to (also) use stderr for its output, am i right? .. not sure .. i tried several coding solutions and examples i found on StackOverflow, but i can't create a working PIPE construction to catch both stderr and stdout .. can you help me with this ?

**Comment by tissatussa** [comment]
i just managed to run CuteChess Cli for my first time :

```bash
~/Apps/cutechess-1.2.0/projects/cli$ ./cutechess-cli -engine cmd=./weiss_v2.1-dev_compiled_HP_4 -engine cmd=./4ku_#39 -each proto=uci tc=10/80 -debug -rounds 10
```

it works : all output is printed by the -debug option .. how did they code that ?

**Comment by kz04px** [comment]
I'm fairly sure that 4ku only ever prints to stdout. If you can paste output that you're having trouble with I'd be happy to look. I don't know why any engine would use stderr for normal engine output, as none of it is an error.

**Comment by tissatussa** [comment]
> If you can paste output that you're having trouble with I'd be happy to look.

thanks, i must think of a way to explain the core problem, to my thinking, giving some python code lines .. i found all kinds of solutions to similar problems / questions, but i feel it must be simple .. indeed stderr should not be needed .. running 4KU in Linux terminal gives no problems but the Popen process is .. eg. i tried to add the attribute stderr=PIPE and even stderr=STDOUT, expecting then all data goes into a same pipe, but my understanding lacks .. the commands `uci` and `ucinewgame` have their proper `isready` / `readyok` ..

the core loop:

```python
def getBM(p, msg):

	p.stdin.write(msg+'\n')
	p.stdin.flush()

	bm = 'bestmove'
	while True:
		s = p.stdout.readline().strip()
		if s.startswith(bm):
			s  = s[len(bm):].strip()
			a  = s.split(' ')
			bm = a[0]
			break

		fnInfoFill(s)  # filter stdout info lines

	return bm  # best move


```

**Comment by tissatussa** [comment]
now i remember where 4KU got stuck - and a few other simple UCI engines have the same issue with my code : it can't process `p.stdout.readline()` , the script doesn't reach `if s.startswith(bm)` .. it looks like `p.stdout.readline()` fails, but i get no error, even when using try except .. well, `stderr` might be blocked also, or it's not properly initiated .. so, if you ask me to show some problematic output : i got none ..
