### ISSUE TITLE
why calculate when only 1 legal move ?

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#45]
many chess engines have this issue .. it's unclear to me why this happens : in such case an engine often thinks for many seconds, which could easily be saved .. btw. i encounter this with 10m+3s games, the only ones i do at this moment.

could there be an easy fix, not taking much byte space, creating this logical and efficient improvement ?

**Comment by kz04px** [comment]
I just wrote a quick attempt at this and I'm seeing about a 35 bytes increase. I don't think there would be much Elo gain from this, but perhaps it's worth keeping in mind or even testing eventually.

The code required is very simple to write, I imagine most engines authors just don't think of it or it's generally not worth the effort.

**Comment by tissatussa** [comment]
ok .. it feels strange though : i guess alls engines start with perft 1 to make a list of all legal moves !?

**Comment by tissatussa** [comment]
-also regarding a recent Discord message : in chess often positions can occur that have only 1 move .. it feels like engines stick to their go wtime btime durations for every move.

**Comment by PGG106** [comment]
this was (lightly) discussed in the SF discord this morning, the conclusion being it doesn't gain elo

**Comment by tissatussa** [comment]
> it doesn't gain elo

i guess your conclusion doesn't count the lost seconds, unneeded .. these might come handy when time is low !?

**Comment by tissatussa** [comment]
btw. i really thought this could be a simple `if nrMoves == 1` at position init ..

**Comment by kz04px** [comment]
> btw. i really thought this could be a simple if nrMoves == 1 at position init ..

4ku and most other engines use pseudolegal move generation. The list of moves needs filtering to find out how many of them are actually legal. `makemove` returns `true` or `false` to tell us whether the resulting position is legal or not. The code ends up looking something a bit like this:
```C++
            int num_legal = 0;
            const int num_moves = movegen(pos, moves, false);
            for (int i = 0; i < num_moves; ++i) {
                auto npos = pos;
                if (makemove(npos, moves[i])) {
                    num_legal++;
                    moves[0] = moves[i];
                }
            }

            if (num_legal == 1) {
                cout << "bestmove " << move_str(moves[0], pos.flipped) << "\n";
            }
```
I find it hard to believe this adds literally no strength at all, but likewise I don't see it adding enough to be worth the size increase.

**Comment by PGG106** [comment]
> i guess your conclusion doesn't count the lost seconds, unneeded .. these might come handy when time is low !?
>>
i haven't ran the test myself but whoever did checked for elo gain, if when low on time this change gained elo it would show up as an elo gain, but since i want first hand evidence of this i'll actually test this (with a very short time control so they are always low on time)

**Comment by tissatussa** [comment]
@kz04px nice code example .. i know pseudolegal moves .. i can imagine the impact on coding this .. in practice you might be right .. anyway, just brainstorming :-)
