### ISSUE TITLE
4KU fails mate

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#90]
i just encountered a strange playing by 4KU : it fails to mate when clearly winning (eval is +296 or so) : it had Queen and kNight to mate a lone opponent King but lost due to the 50-move rule .. i never saw that with previous versions .. i tried to reproduce this by re-entering such position (by the CuteChess opening book feature) but then 4KU plays well : it mates !? Here is a ZIPped pgn [4KU-fails-mate.zip](https://github.com/kz04px/4ku/files/10277644/4KU-fails-mate.zip) the first game is the original, the other 2 games start after move 74 to setup such winning endgame position.

**Comment by gcp** [comment]
I think this is fully expected. The mate scores are stored in the TT without correcting for the ply depth and there's no 50-move rule implementation.

Fixing those things takes bytes, it's not clear it would actually be stronger.

That said, I checked and OpenBench uses resigning and does so quite early, so if this has gotten bad enough to hurt the engine we wouldn't see it there. That might be worth crosschecking.

**Comment by tissatussa** [comment]
> ..OpenBench uses resigning and does so quite early..

i guess OpenBench is part of that TCEC tournament ? then i understand .. 4KU eval went upto +296.41 =the max ? Could the "problem" then easily be solved by striving for a higher max ?
Btw. 4KU has no 'mate score' like +M4

**Comment by gcp** [comment]
OpenBench is what the patches are tested on. I'm not sure whether TCEC will use resigning, but it's possible they wont, in which case this is relevant.

>Btw. 4KU has no 'mate score' like +M4

Takes up bytes for no strength gain.

I just finished my tests. I played ~3000 games versus Fruit 2.1 (2684 CCRL) with resigning and TB adjudication, and ended up with a score of about ```-70 +- 10 Elo```. I then played the match again with resigning and adjudication disabled and ended up at ```-85 +- 10 Elo```. So we may lose about 15 Elo due to not being able to mate sometimes, which means we can spend about 30 to 45 bytes on a solution.

**Comment by gcp** [comment]
I repeated this test today, again playing 3000 games to re-calibrate for the https://github.com/kz04px/4ku/tree/TT-mate-scores branch.

Both matches (with and without resigning) ended up at ```-55 Elo``` compared to ```Fruit 2.1```, so there's no evidence this issue has any strength impact.

The ```TT-mate-scores``` branch, against Fruit 2.1 with no resigning, ended at:
```
Score of 4ku vs Fruit 2.1: 931 - 1373 - 696  [0.426] 3000
...      4ku playing White: 533 - 623 - 344  [0.470] 1500
...      4ku playing Black: 398 - 750 - 352  [0.383] 1500
...      White vs Black: 1283 - 1021 - 696  [0.544] 3000
Elo difference: -51.6 +/- 11.0, LOS: 0.0 %, DrawRatio: 23.2 %
```
So again, not much evidence there's a real issue, I guess?

**Comment by tissatussa** [comment]
thanks for taking the effort testing this .. to me it seemed a severe error, but i understand your reasoning and conclusion .. good luck at the tournament!
